// Data layer for the Utah Privacy Workbench (the operational-application demo).
// Sample/illustrative data; the marriage-license model remains the validated hero.

export type WorkbenchView =
  | "dashboard"
  | "inventory"
  | "review"
  | "models"
  | "compare"
  | "versions"
  | "redaction"
  | "sedi";

export type ReviewType = "qa_flag" | "legislative" | "inconsistency";

export interface ReviewItem {
  id: string;
  type: ReviewType;
  title: string;
  entity: string;
  functionName: string;
  preview: string;
  /** confidence (qa) or jurisdiction count (inconsistency) shown on the row */
  meta: string;
  /** which detail view this item drills into */
  opens: Extract<WorkbenchView, "review" | "versions" | "compare">;
}

export const REVIEW_TYPE_LABEL: Record<ReviewType, string> = {
  qa_flag: "QA flag",
  legislative: "Legislative change",
  inconsistency: "Inconsistency",
};

/** Tailwind classes for each review-type tag. */
export const REVIEW_TYPE_STYLE: Record<ReviewType, string> = {
  qa_flag: "bg-amber-100 text-amber-700",
  legislative: "bg-violet-100 text-violet-700",
  inconsistency: "bg-rose-100 text-rose-700",
};

/** Base queue — always present (2 QA flags + 1 legislative). */
export const REVIEW_QUEUE: ReviewItem[] = [
  {
    id: "rq-bizlic-orem",
    type: "qa_flag",
    title: "Secondary Classification",
    entity: "Orem City",
    functionName: "Business License",
    preview: "Private — owner SSN / EIN and home address are protected under § 63G-2-302.",
    meta: "71% conf",
    opens: "review",
  },
  {
    id: "rq-death",
    type: "qa_flag",
    title: "Secondary Classification",
    entity: "Utah DHHS",
    functionName: "Death Certificate",
    preview: "Private — cause of death and SSN are protected under § 26B-8-119.",
    meta: "71% conf",
    opens: "review",
  },
  {
    id: "rq-hb412",
    type: "legislative",
    title: "Proposed update v2 — retention & SSN access",
    entity: "Utah County",
    functionName: "Marriage Licenses",
    preview:
      "Hypothetical Utah H.B. 412 caps active retention at 75 years and re-scopes SSN access to DHHS / ORS. Awaiting your sign-off.",
    meta: "2 fields",
    opens: "versions",
  },
];

/** Surfaced only after the cross-jurisdiction consistency scan runs. */
export const REVIEW_INCONSISTENCIES: ReviewItem[] = [
  {
    id: "rq-inc-ssn",
    type: "inconsistency",
    title: "Owner SSN / EIN — Public vs Private",
    entity: "13 municipalities",
    functionName: "Business Licenses",
    preview: "The same identifier is classified Public in 1 jurisdiction but Private in 12 — unequal protection for identical data.",
    meta: "13 jurisdictions",
    opens: "compare",
  },
  {
    id: "rq-inc-retention",
    type: "inconsistency",
    title: "Contractor SSN retention varies",
    entity: "9 municipalities",
    functionName: "Building Permits",
    preview: "Retention for the same record ranges from 5 years to permanent across 9 cities.",
    meta: "9 jurisdictions",
    opens: "compare",
  },
  {
    id: "rq-inc-address",
    type: "inconsistency",
    title: "Owner home address — Public vs Private",
    entity: "9 cities",
    functionName: "Dog Licenses",
    preview: "§ 63G-2-302 applied inconsistently: address Public in 3 cities, Private in 6.",
    meta: "9 jurisdictions",
    opens: "compare",
  },
];

export interface ActivityEvent {
  text: string;
  when: string;
  dot: string; // hex
}

export const ACTIVITY: ActivityEvent[] = [
  { text: "Marriage License model generated by 10-agent orchestration", when: "12 min ago", dot: "#0EA5E9" },
  { text: "QA flagged SSN classification for human review", when: "12 min ago", dot: "#E8852B" },
  { text: "Legislative monitor detected H.B. 412 (illustrative)", when: "1 hr ago", dot: "#7C3AED" },
  { text: "Consistency scan flagged Business License across 2 jurisdictions", when: "2 hr ago", dot: "#F43F5E" },
];

export const DASHBOARD = {
  governedCount: 1284,
  statewideTotal: 14000,
  generatingCount: 3,
  coveragePct: "9%",
};

// ---- Governance Inventory tree (entity-type → office → function → record) ----

export type InvStatus = "published" | "in_review" | "needs_update" | "not_modeled";

export const INV_STATUS_LABEL: Record<InvStatus, string> = {
  published: "Published",
  in_review: "In review",
  needs_update: "Needs update",
  not_modeled: "Not modeled",
};

export const INV_STATUS_STYLE: Record<InvStatus, string> = {
  published: "bg-emerald-100 text-emerald-700",
  in_review: "bg-amber-100 text-amber-700",
  needs_update: "bg-rose-100 text-rose-700",
  not_modeled: "bg-slate-100 text-slate-500",
};

/** Published-models library (portfolio of finished, human-approved artifacts). */
export interface ModelCard {
  id: string;
  title: string;
  entity: string;
  office: string;
  version: number;
  fields: number;
}

export const MODELS: ModelCard[] = [
  { id: "marriage", title: "Marriage License", entity: "Utah County", office: "County Clerk", version: 1, fields: 8 },
  { id: "building", title: "Building Permit", entity: "Provo City", office: "Building & Zoning", version: 1, fields: 8 },
  { id: "business", title: "Business License", entity: "Salt Lake County", office: "Business Licensing", version: 1, fields: 8 },
];

export interface InvNode {
  id: string;
  label: string;
  sublabel?: string; // e.g., office responsible, on a leaf
  status?: InvStatus; // leaves only
  version?: number;
  children?: InvNode[];
}

/** Only entity-type-applicable functions appear — no school-district marriage licenses. */
export const INVENTORY: InvNode[] = [
  {
    id: "county",
    label: "County",
    children: [
      {
        id: "county-clerk",
        label: "Clerk / Auditor",
        children: [
          {
            id: "county-marriage",
            label: "Marriage Licenses",
            children: [
              { id: "rec-marriage", label: "Marriage License", sublabel: "County Clerk", status: "published", version: 1 },
            ],
          },
          {
            id: "county-voter",
            label: "Voter Registration",
            children: [
              { id: "rec-voter", label: "Voter Registration Record", sublabel: "County Clerk", status: "not_modeled" },
            ],
          },
          {
            id: "county-biz",
            label: "Business Licensing",
            children: [
              { id: "rec-bizlic-county", label: "Business License Application", sublabel: "Clerk/Auditor", status: "needs_update", version: 1 },
            ],
          },
        ],
      },
      {
        id: "county-recorder",
        label: "Recorder",
        children: [
          {
            id: "county-property",
            label: "Property Records",
            children: [
              { id: "rec-deed", label: "Deed of Trust", sublabel: "County Recorder", status: "not_modeled" },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "municipality",
    label: "Municipality",
    children: [
      {
        id: "muni-biz",
        label: "Business Licensing",
        children: [
          {
            id: "muni-biz-fn",
            label: "Business Licensing",
            children: [
              { id: "rec-bizlic-orem", label: "Business License Application", sublabel: "Orem City", status: "published", version: 1 },
            ],
          },
          {
            id: "muni-building",
            label: "Building Permits",
            children: [
              { id: "rec-permit", label: "Building Permit", sublabel: "Community Development", status: "not_modeled" },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "school",
    label: "School District",
    children: [
      {
        id: "school-records",
        label: "Student Records",
        children: [
          {
            id: "school-ed",
            label: "Education Records (FERPA)",
            children: [
              { id: "rec-ferpa", label: "Student Education Record", sublabel: "Registrar", status: "in_review" },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "state",
    label: "State Agency",
    children: [
      {
        id: "state-health",
        label: "Health & Human Services",
        children: [
          {
            id: "state-vital",
            label: "Vital Records",
            children: [
              { id: "rec-death", label: "Death Certificate", sublabel: "Vital Records", status: "not_modeled" },
            ],
          },
        ],
      },
    ],
  },
];
